### ISSUE TITLE
A potential bug with CNF Examples while using Ganak

### ISSUE THREAD

**Issue by Annlean** [meelgroup/ganak#28]
Hi!
I recently encountered an issue while utilizing Ganak. I attempted to process two CNF files using Ganak. I set the timeout of running the model counter to 600 seconds. 
The origin.cnf file can be processed soon while the new.cnf file cannot stop withing 600 seconds. The two files differ by only one clause (origin.cnf is "64 -92 -5 -62 38 0" while new.cnf is "64 -92 -92 -5 -62 38 0") and produce completely opposite results. To assist the diagnosis, I conducted further tests: the critical clause "64 -92 -92 -5 -62 38 0" and the key variable "92" in new.cnf, which seem to be causing the timeout. 
I think Ganak may have a potential bug, and I hope this information can assist you to address the potential bugs. The two example files are attached [here](https://drive.google.com/drive/folders/1z5Kt3AMvekUwME3uAWey9bEte6WcBk0F?usp=sharing) for your reference.
Best regards,

Haiyan and Jifeng
CSTAR group

**Comment by msoos** [comment]
Hi,

Yeah, this version of GANAK is actually not great, I think it may have some issues such as what you pointed out above. I'll talk with my colleagues what to do -- we actually have a newer version that has these issues fixed. You can use it here:
[ganak.gz](https://github.com/meelgroup/ganak/files/14808920/ganak.gz)

Can you please check with this GANAK whether the bug is still there? It should also be significantly faster. Thanks,

Mate

PS: Please note that this version of GANAK is currently confidential.

**Comment by Annlean** [comment]
Hi,
The bugs no longer exist in the new version of ganak, and the new ganak performs very well and is significantly faster. Thank you for your work! Thanks for your reply!

**Comment by msoos** [comment]
Glad to hear!

**Comment by Annlean** [comment]
There are still some problems with the current ganak version on Github. For example, "[2] 446164 segmentation fault (core dumped) ./ganak" will appear when running benchmarks/toy3.cnf.
Looking forward you can update github after the latest ganak related work is completed.

**Comment by msoos** [comment]
As stated before, we are well aware of the issues with the GitHub version. I can fuzz it and generated millions of bugs. Please do not report any further bugs, until the github repo has been updated.  Thanks for your patience.
