### ISSUE TITLE
Request for a custom release

### ISSUE THREAD

**Issue by SAuppp** [meelgroup/ganak#30]
I want to use ganak to get actual #solutions of this [benchmark](https://zenodo.org/records/3793090). These instances already contain independent supports so I want to use them to save times.

But it seems ganak can only recognize independent support in one line, the latest "c ind" line will overwrite previous "c ind" line.

Could you please modify a little bit (like change some "assignment operation" to "push_back"?), and make another release.

Thanks a lot.

Here is an example picture which may help you get me better.

c ind 1787 1788 1789 1790 1791 0 
c ind 1772 1773 1774 1775 1776 0 
c ind 1767 1768 1769 1770 1771 0 
c ind 1782 1783 1784 1785 1786 0 
c ind 1762 1763 1764 1765 1766 0 
c ind 1757 1758 1759 1760 1761 0 
c ind 1752 1753 1754 1755 1756 0 
c ind 1747 1748 1749 1750 1751 0 
c ind 1777 1778 1779 1780 1781 0

 
this won't work

`c ind 1787 1788 1789 1790 1791 1772 1773 1774 1775 1776 1767 1768 1769 1770 1771 1782 1783 1784 1785 1786 1762 1763 1764 1765 1766 1757 1758 1759 1760 1761 1752 1753 1754 1755 1756 1747 1748 1749 1750 1751 1777 1778 1779 1780 1781 0`
this will work

**Comment by msoos** [comment]
Hi,

I have now updated the CryptoMiniSat repository so it can parse those files. However, you should prefer using this ganak version:

https://www.msoos.org/largefiles/ganak-v2.3-amd64

which is a statically built linux executable. It should be _significantly_ faster than the version you find in this repository. It is the version that was used at the Model Counting Competition of 2024, but in a way that's MUCH easier to use (the version at the competition needs a very large number of options to be set). This ganak can simply be used like:

```
./ganak-v2.3-amd64 myfile.cnf
```

And it will always do the right thing.

In case you are happy with approximate counts, you can use: https://www.msoos.org/largefiles/approxmc-amd64 It can be used via:

```
./approxmc-amd64 myfile.cnf
```

Please use these versions, they should be a lot faster. Old Ganak can also accidentally return some incorrect answers due to a number of bugs. These versions have been fuzz-tested to be correct.

Let me know how it goes. If you encounter any issues, bugs, things that don't seem OK, please let me know. I am keeping this issue open so you can report any issues here.

I hope the above helped,

Mate

**Comment by SAuppp** [comment]
Thanks, Mate.

By the way, why do these release (like ganak and approxmc) not appear in the repositories? Are the codes in repos not the latest version? How can I do it if I want to do some modification to suit my case.

**Comment by msoos** [comment]
Hi,

If you need access, let me know, I can give access to everything you need to build this. We are not trying to hide it, actually. However, double-blind requirements mean that if I put that code here, we will actually be violating double-blind requirements and make it impossible for us to publish what we have done. Yes, this sounds wrong, but not all systems are right.  This one, in particular, is not right. So we live with it.

Let me know if you want access, I'll give it without any issues. However, it's not so easy to compile the newest Ganak -- it actually integrates a large number of libraries. The GitHub Action actually builds it without issues, so there is a well-documented, working way of compiling it, but it will take you some time to compile. Also note that you will need to compile it for "Release" if you do get access to the repository, otherwise it'll be about 10% slower than the binary I linked to. The binary I linked to actually shows all git hashes, so you could make 100% sure that it matches exactly what you have access to. I am trying to make this as transparent as possible.

I hope the above helps to explain,

Mate

PS: I 100% believe in open science, and I am aware that I am paid by taxpayer's money, so I always make my stuff open as much as possible. Here, it's simply not yet possible. It sucks, honestly. Once our paper is accepted, of course all of this will be public.

**Comment by SAuppp** [comment]
Hi, Mate.

I have great respect for you and your work, and I strongly believe in your spirit of open-source.

I was just wondering how I might customize certain features, such as modifying the timeout limit. I'm embarrassed to have your involvement in such tiny detail, it could be annoying for you. So as I originally hoped to dive into the code myself and make the necessary adjustments.

But since the latest code cannot be released due to double-blind review requirements, could you please let me know how I can set the timeout limit? Is it a runtime parameter or something that needs to be modified in the source code?

At last, if my careless and irresponsible inquiries caused you any inconvenience, please accept my sincere apologies. I truly regret any trouble it may have caused.

**Comment by msoos** [comment]
Hey,

I'm glad you asked, and you should have no problems asking. I remember going to the Nix channel once, and I said the same thing, about being sorry to have asked so many questions, and their response still sits in my mind: basically, you should not feel bad for asking, ever.

OK, with that out of it way, the best way to limit the time is actually with the built-in tool timeout, it's part of GNU coreutils: https://linuxize.com/post/timeout-command-in-linux/  You can use it as such:

```
timeout 300 ./ganak-v2.3-amd64 myfile.cnf
```

Then it will run for at most 5 minutes. You can even combine this with `/usr/bin/timeout --verbose` which is also part of GNU, and you can install via `apt-get install time` or similar:

```
$ /usr/bin/time --verbose timeout 5 ./ganak 140.cnf
[...]
Command exited with non-zero status 124
        Command being timed: "timeout 5 ./ganak --td 0 140.cnf"
        User time (seconds): 4.94
        System time (seconds): 0.05
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:05.00
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 86292
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 17023
        Voluntary context switches: 4
        Involuntary context switches: 30
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 124
```

Notice that it ran 4.95s in userland and 0.05s in system (probably IO for reading the file). Total was exactly 5 seconds. It also gave some useful information on e.g. max physical mem used, among other things. I run ganak always under `/usr/bin/time --verbose` because it helps in debugging, for example it also shows the signal that got triggered, 14 here, which happens to be SIGALRM, the signal emitted by `timeout` when time is up. Note that `time` and `/usr/bin/time` are actually two different things, and `/usr/bin/time` is waaaay better :)

It's helpful to use these GNU utilities, they tend to be more reliable and more portable than e.g. writing one into the tool itself.

I hope the above helped, and let me know if you have any more questions or if you need access to the source code,

Mate
